### ISSUE TITLE
what is the license of this library

### ISSUE THREAD

**Issue by ghost** [a-n-t-h-o-n-y/Twitter-API-C-Library#11]
could you please add license, so i can use it for commercial app (maybe for commercial).
what is the licenses, Thanks

iam happy when i read the twitter is reference to this library, so i think this library is official from twitter
[https://developer.twitter.com/en/docs/twitter-api/tools-and-libraries](url)

**Comment by a-n-t-h-o-n-y** [comment]
Added the MIT License: https://github.com/a-n-t-h-o-n-y/Twitter-API-C-Library/commit/294b4c6f0fd41ffa27d3fdd98ef00cca6e34e19b
