### ISSUE TITLE
CMake error: INTERFACE_LINK_LIBRARIES may not contain link-type keyword   "optimized".

### ISSUE THREAD

**Issue by KiwiDch** [a-n-t-h-o-n-y/Twitter-API-C-Library#5]
Hi, i tried to build the lib on cmake(gui) on windows and i have this error:

`Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
CMake Error at CMakeLists.txt:20 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.

CMake Error at networklib/CMakeLists.txt:34 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.

Found OpenSSL: optimized;D:/Documents/Code/Ressources/Openssl/SHARED/x64/release/libcrypto.lib;debug;D:/Documents/Code/Ressources/Openssl/SHARED/x64/debug/libcrypto.lib (found version "3.0.0")  
CMake Error at networklib/CMakeLists.txt:41 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.

Configuring incomplete, errors occurred!
See also "D:/Documents/Code/Ressources/Twitter/Compile-twitter-API-C/CMakeFiles/CMakeOutput.log".
See also "D:/Documents/Code/Ressources/Twitter/Compile-twitter-API-C/CMakeFiles/CMakeError.log".`

I can't find anything to resolve this error on the internet and i don't know why there is this error
Thanks

**Comment by a-n-t-h-o-n-y** [comment]
Hi, I'm not developing on a Windows machine, and can't replicate this, I have made a small change to the cmake files there.

https://github.com/a-n-t-h-o-n-y/Twitter-API-C-Library/commit/e726800ad0a6d692f57717e865e7454aa51706a8
https://github.com/a-n-t-h-o-n-y/Twitter-API-C-Library/commit/0cb30da4352bd8f30bdd2def51a17c844b0a4e66
