### ISSUE TITLE
Custom import target for Boost headers is painful

### ISSUE THREAD

**Issue by HunterZ** [a-n-t-h-o-n-y/Twitter-API-C-Library#8]
TwitterLibrary is dependent on Boost headers, and it currently satisfies the dependency by synthesizing a `boost` import target and then linking against that. This is OK for an application, but is a huge pain point when done in a CMake library: CMake records the custom `boost` import target as a dependency in TwitterLibrary's generated import modules, but doesn't propagate the `boost` import target definition (this is a limitation of CMake's import module generator). This forces each downstream project to copy-paste TwitterLibrary's custom `boost` import target definition CMake goop in order to satisfy TwitterLibrary's stated dependency.

Fortunately, there may be an easy way to address this: CMake's `find_package` module for Boost already creates a `Boost::boost` import target that TwitterLibrary may be able to link against in lieu of defining the custom import target. See https://cmake.org/cmake/help/latest/module/FindBoost.html#imported-targets

**Comment by a-n-t-h-o-n-y** [comment]
I've updated the CMake config in the latest commit(https://github.com/a-n-t-h-o-n-y/Twitter-API-C-Library/commit/3d43fa6a2fe5931a404e8fc872d4a092de0a703a). Hope this solves the issue.

Just a note that the warning level is higher and more warnings appear when building now, these will be handled soon.
